services:
  postgres:
    image: postgres:16-alpine
    container_name: retailedge-db
    environment:
      POSTGRES_USER: retailedge
      POSTGRES_PASSWORD: retailedge_dev
      POSTGRES_DB: retailedge_dev
    ports:
      - "5433:5432"
    volumes:
      - retailedge_pgdata:/var/lib/postgresql/data
      - ./docker/init-databases.sh:/docker-entrypoint-initdb.d/init-databases.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U retailedge -d retailedge_dev"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  retailedge_pgdata:
